version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"    # Expose port 3000 to the host
    volumes:
      - ./uploads:/usr/src/app/uploads  # Mount the uploads directory inside the container (optional)
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/dogdb  # MongoDB URI (if you're using MongoDB in the app)
    networks:
      - app-network
    depends_on:
      - mongo   # Wait for MongoDB to be available before starting the app

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
